---

- name: Ubuntu desktop environment playbook
  hosts: localhost
  vars:
    - go_version: 1.8
  environment:
    DEBIAN_FRONTEND: noninteractive
  pre_tasks:
    - name: check .gvm does not exist
      stat:
        path: ~/.gvm
      register: stat_gvm_result

  roles:
    # Common roles
    # - { role: locales, become: true }
    - { role: common, become: true }
    # - { role: zsh, become: true }
    # - { role: dotfiles, become: true }
    # - { role: java-openjdk, become: true }
    # - { role: phantomjs, become: true }
    # - { role: projects-installer }
    # Server roles
    # - { role: apache2, become: true }
    # - { role: apache2-php, become: true }
    # - { role: beanstalkd, become: true }
    # - { role: blackfire, become: true }
    # - { role: composer, become: true }
    - { role: docker, become: true }
    # - { role: elasticsearch, become: true }
    # - { role: exim, become: true }
    # - { role: fail2ban, become: true }
    - role: suzuki-shunsuke.gvm
      when: stat_gvm_result.stat.exists == False
    - role: suzuki-shunsuke.gvm-module
    # - { role: gvm, become: true }
    - { role: nodejs, become: true }
    - { role: python, become: true }
    # - { role: rbenv, become: true }
    - { role: ssh, become: true }
    # Desktop roles
    # - { role: desktop, become: true }
    - { role: desktop-cleanup, become: true }
    # - { role: desktop-autostart, become: true }
    # - { role: desktop-preferences-unity }
    - { role: atom, become: true }
    - { role: cmprescott.chrome, become: true }
    - { role: gdrive, become: true }
    # - { role: remmina, become: true }
    # - { role: skype, become: true }
    # - { role: smartgit, become: true }
    # - { role: spotify, become: true }
    # - { role: teamviewer, become: true }
    - { role: vagrant, become: true }
    - { role: virtualbox, become: true }
    # - { role: wine, become: true }
    # bspwm
    # - { role: sxhkd, become: true }
    # - { role: bspwm, become: true }
    # - { role: bspwm-panel, become: true }
    # - { role: bspwm-environment, become: true }
    # User roles
    # - { role: gulp}
    # - { role: browsersync }
    # - { role: bower }
    # - { role: webpack }

  tasks:
    - name: update git config globally setting user.email
      command: git config --global user.email mc.matthew.cosgrove@gmail.com
    - name: update git config globally setting user.name
      command: git config --global user.name matthewcosgrove
    - name: Install libgnome-keyring-dev for git credential helper
      apt: pkg=libgnome-keyring-dev state=latest
      become: true
    - name: Set up gnome-keyring for git credential helper
      command: make --directory=/usr/share/doc/git/contrib/credential/gnome-keyring
      become: true
    - name: Set up git credential helper
      git_config:
        name: credential.helper
        scope: global
        value: /usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring
    - name: Set up git to suppress message on push
      git_config:
        name: push.default
        scope: global
        # value: simple
    - name: gvm install go{{go_version}} --binary
      gvm:
        version: go{{go_version}}
        gvm_root: "~/.gvm"
        binary: yes
