---

- name: Ubuntu desktop environment playbook
  hosts: localhost
  vars:
    - go_version: 1.8
  environment:
    DEBIAN_FRONTEND: noninteractive
  pre_tasks:
    - name: check .gvm does not exist
      stat:
        path: ~/.gvm
      register: stat_gvm_result
    - name:  add apt repo for git
      become: true
      apt_repository:
        repo: ppa:git-core/ppa
    - name:  update apt packages
      become: true
      apt:
        update_cache: yes
    - name:  install latest git
      become: true
      package:
        name: git
        state: latest
    - name:  install latest curl
      become: true
      package:
        name: curl
        state: latest
    - name:  install latest bison
      become: true
      package:
        name: bison
        state: latest
  roles:
    # Common roles
    # - { role: locales, become: true }
    # - { role: common, become: true }
    # - { role: zsh, become: true }
    # - { role: dotfiles, become: true }
    # - { role: java-openjdk, become: true }
    # - { role: phantomjs, become: true }
    # - { role: projects-installer }
    # Server roles
    # - { role: apache2, become: true }
    # - { role: apache2-php, become: true }
    # - { role: beanstalkd, become: true }
    # - { role: blackfire, become: true }
    # - { role: composer, become: true }
    - { role: docker, become: true }
    # - { role: elasticsearch, become: true }
    # - { role: exim, become: true }
    # - { role: fail2ban, become: true }
    - role: suzuki-shunsuke.gvm
      when: stat_gvm_result.stat.exists == False
    - role: suzuki-shunsuke.gvm-module
    # - { role: gvm, become: true }
    # - { role: hhvm, become: true }
    # - { role: mailcatcher, become: true }
    # - { role: mailhog, become: true }
    # - { role: memcached, become: true }
    # - { role: mysql57, become: true }
    # - { role: mysql56, become: true }
    # - { role: nginx, become: true }
    # - { role: nginx-php-fpm, become: true }
    - { role: nodejs, become: true }
    # - { role: php, become: true }
    # - { role: php-pecl, become: true }
    # - { role: php-phar-tools, become: true }
    - { role: python, become: true }
    # - { role: redis, become: true }
    # - { role: rbenv, become: true }
    - { role: ssh, become: true }
    # Desktop roles
    # - { role: desktop, become: true }
    - { role: desktop-cleanup, become: true }
    # - { role: desktop-autostart, become: true }
    # - { role: desktop-preferences-unity }
    # - { role: adapta-theme, become: true }
    # - { role: albert, become: true }
    # - { role: altyo, become: true }
    # - { role: arc-theme, become: true }
    - { role: atom, become: true }
    - { role: cmprescott.chrome, become: true }
    # - { role: chromium, become: true }
    # - { role: claws-mail, become: true }
    # - { role: compton, become: true }
    # - { role: copyq, become: true }
    # - { role: dbeaver, become: true }
    # - { role: filezilla, become: true }
    # - { role: firefox, become: true }
    # - { role: flatabulous, become: true }
    - { role: gdrive, become: true }
    # - { role: geary, become: true }
    # - { role: gimp, become: true }
    # - { role: grub-customizer, become: true }
    # - { role: hubic, become: true }
    # - { role: indicator-sysmonitor, become: true }
    # - { role: ksuperkey, become: true }
    # - { role: libreoffice, become: true }
    # - { role: maim, become: true }
    # - { role: min, become: true }
    # - { role: mysql-workbench, become: true }
    # - { role: nautilus-plugins, become: true }
    # - { role: nemo, become: true }
    # - { role: notepadqq, become: true }
    # - { role: notify-osd, become: true }
    # - { role: qutebrowser, become: true }
    # - { role: remarkable, become: true }
    # - { role: remmina, become: true }
    # - { role: ripgrep, become: true }
    # - { role: rofi, become: true }
    # - { role: shutter, become: true }
    # - { role: sift, become: true }
    # - { role: slop, become: true }
    # - { role: skype, become: true }
    # - { role: smartgit, become: true }
    # - { role: spotify, become: true }
    # - { role: sublime3, become: true }
    # - { role: sunflower, become: true }
    # - { role: teamviewer, become: true }
    # - { role: thunderbird, become: true }
    # - { role: ultra-flat-icons, become: true }
    # - { role: urxvt-perls }
    - { role: vagrant, become: true }
    - { role: virtualbox, become: true }
    # - { role: vokoscreen, become: true }
    # - { role: wine, become: true }
    # - { role: workrave, become: true }
    # - { role: xfce-dockbarx, become: true }
    # - { role: xmind, become: true }
    # bspwm
    # - { role: sxhkd, become: true }
    # - { role: bspwm, become: true }
    # - { role: bspwm-panel, become: true }
    # - { role: bspwm-environment, become: true }
    # User roles
    # - { role: gulp}
    # - { role: browsersync }
    # - { role: bower }
    # - { role: webpack }

  tasks:
    - name: Install libgnome-keyring-dev for git credential helper
      apt: pkg=libgnome-keyring-dev state=latest
      become: true
    - name: Set up gnome-keyring for git credential helper
      command: make --directory=/usr/share/doc/git/contrib/credential/gnome-keyring
      become: true
    - name: Set up git credential helper
      git_config:
        name: credential.helper
        scope: global
        value: /usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring
    - name: Set up git to suppress message on push
      git_config:
        name: push.default
        scope: global
        # value: simple
    - name: gvm install go{{go_version}} --binary
      gvm:
        version: go{{go_version}}
        gvm_root: "~/.gvm"
        binary: yes
