---

- name: Installing apt-key
  apt_key: url=https://packagecloud.io/AtomEditor/atom/gpgkey state=present

- name: Add atom official package repository as described in https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux
  shell: sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'

# - name: Add Atom repository (Webupd8team)
#   apt_repository: repo="ppa:webupd8team/atom" state=present

- name: Install Atom text editor
  apt: name=atom state=present update_cache=yes

# - name: Setup Atom Packages
#   apm: name=sync-settings # All others packages are managed by sync-settings
#   become: true
#   become_user: "{{ ansible_env.USER }}"
